#!/bin/bash
#
# AUTOR: PK Ernandes
# EMAIL: suporte@ernandes.info
#
#

function :disk(){

  set --
  disks=$(ls /sys/class/block/ | grep -v -E 'hd[a-z][1-9]|sd[a-z][1-9]|nvme[a-z][1-9]|dm-[0-9]|loop[0-9]|sr[0-9]|fd[0-9]|ram[0-9]')
  for disk in ${disks}; do
    size=$(head /sys/class/block/"${disk}"/size)
    size_gb=$((${size} / 2 / 1024 / 1024))
    out="/dev/${disk};${size_gb}"
    set -- $@ $out
  done

  echo
  printf "%s\n" "----;--------" "${@}" | column -t -s';' --table-columns 'disk,size(gb)'; echo
}


# vim:set ts=2 sts=2 sw=2 et ft=sh:
