#!/bin/bash
#
# AUTOR: PK Ernandes
# EMAIL: suporte@ernandes.info
#
#

function :os(){

  set --
#  test -f "/etc/os-release" && echo; cat /etc/os-release; echo || echo ' error - file "/etc/os-release" not found!\n'
  if test -f "/etc/os-release"; then
    . /etc/os-release
    hostname=$(hostname)
    machine_id=$(head -n1 /etc/machine-id)
    set -- "name;$NAME" \
    "version;$VERSION_ID" \
    "hostname;$hostname" \
    "machine-id;$machine_id"
  else
    set -- "error;file "/etc/os-release" not found!"
  fi

  echo
  printf "%s\n" "----;-----" "${@}" | column -t -s';' --table-columns name,value; echo

}


# vim:set ts=2 sts=2 sw=2 et ft=sh:
